$schema: "http://json-schema.org/draft-04/schema#"

description: snakemake configuration file

type: object

properties:
  samples:
    type: string
  units:
    type: string
  ped:
    type: string
    description:
      Path to PED file indicating familial relationships and phenotype status.
      If provided PED will be passed to genotyping commands and peddy will be
      run as part of QC.
  ref:
    type: object
    properties:
      species:
        type: string
        description:
            Ensembl species name - required for downloading VEP cache and
            optionally for downloading genome and variation data.
      build:
        type: string
        description:
            Ensembl genome build - required for downloading VEP cache and
            optionally for downloading genome and variation data.
      release:
        type: integer
        description:
            Ensembl release number - required for downloading VEP cache and
            optionally for downloading genome and variation data.
      fasta_url:
        type: string
        description:
            URL to reference genome fasta. If provided species/build/release
            will be ignored and genome fasta will be downloaded from this URL
            instead.
      variation_url:
        description:
            URL to a bgzip compressed VCF of common variation. If provided
            species/build/release will be ignored and variants will be
            downloaded from this URL instead.
        type: string
      fasta_local:
        description:
            Path to local copy of reference genome fasta.  If provided
            species/build/release/fasta_url will be ignored and this file will
            be used instead.
        type: string
      variation_local:
        description:
            Path to local copy of a bgzip compressed VCF of common variation.
            If provided species/build/release/variation_url will be ignored and
            this variant file will be used instead.
        type: string
      add_chr:
        type: boolean
        description:
            If true, add chr prefix to variation VCF after downloading. Only
            applicable to VCF from variation_url, VCF from variation_local will
            be unchanged.
      fix_non_iupac:
        type: boolean
        description:
            If true, check and remove non IUPAC codes from variation.
    required:
      - species
      - build
      - release

      

  filtering:
    type: object
    properties:
      vqsr:
        type: boolean
        description:
            Perform VQSR instead of hard filtering?
      recal:
        type: object
        description:
            Resources and parameters for VQSR.
        required:
          - annotations
          - resources
          - truth_sensitivity
        properties:
          truth_sensitivity:
            type: object
            snvs:
              type: number
            indels:
              type: number
            required:
              - snvs
              - indels
          annotations:
            description:
                Arrays of annotations to add to -an argument of GATK
                VariantRecalibrator for SNV and indel filtering respectively.
            properties:
              snvs:
                type: array
                items:
                  type: string
              indels:
                type: array
                items:
                  type: string
          required:
            - snvs
            - indels
          resources:
            type: object
            description:
                Path to local copy of files for VQSR. Required if vqsr is true.
                You may optionally specify values for priors to use during
                variant recalibration instead of using the defaults as per the
                GATK recommendations.
            properties:
              hapmap:
                type: object
                properties:
                  prior:
                    type: number
                  file:
                    type: string
                  required:
                    - file
              omni:
                type: object
                properties:
                  prior:
                    type: number
                  file:
                    type: string
                  required:
                    - file
              g1k:
                type: object
                properties:
                  prior:
                    type: number
                  file:
                    type: string
                  required:
                    - file
              dbsnp:
                type: object
                properties:
                  prior:
                    type: number
                  file:
                    type: string
                  required:
                    - file
            type: object
            properties:
              mills:
                type: object
                properties:
                  prior:
                    type: number
                  file:
                    type: string
                  required:
                    - file
              axiom:
                type: object
                properties:
                  prior:
                    type: number
                  file:
                    type: string
                  required:
                    - file
            required:
              - hapmap
              - omni
              - g1k
              - dbsnp
              - axiom
              - mills
      hard:
        type: object
        properties:
          snvs:
            type: string
            description:
                JEXL expression for SNP filtering.
          indels:
            type: string
            description:
                JEXL expression for INDEL filtering.
        required:
          - snvs
          - indels
    required:
      - vqsr
      - hard

  processing:
    type: object
    properties:
      remove-duplicates:
        type: boolean
      restrict-regions:
        type: string
      region-padding:
        type: integer
    required:
      - remove-duplicates

  params:
    type: object
    properties:
      gatk:
        type: object
        properties:
          HaplotypeCaller:
            type: string
          BaseRecalibrator:
            type: string
          GenotypeGVCFs:
            type: string
          VariantRecalibrator:
            type: object
            properties:
              snvs:
                type: string
              indels:
                type: string
        required:
          - HaplotypeCaller
          - BaseRecalibrator
          - GenotypeGVCFs
          - VariantRecalibrator
      picard:
        type: object
        properties:
          MarkDuplicates:
            type: string
        required:
          - MarkDuplicates
    required:
      - gatk
      - picard
required:
  - samples
  - units
  - ref
  - filtering
  - processing
  - params
